### ISSUE TITLE
Protractor issue running reports: Setting randomizeTests directly is deprecated, please use the random option in `configure`

### ISSUE THREAD

**Issue by Adalid07** [jasmine/jasmine.github.io#111]
Guys:
I'm trying to generate a report in protractor, but i'm having getting this error:

DEPRECATION: Setting randomizeTests directly is deprecated, please use the random option in `configure`
DEPRECATION: Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`

Someone knows how to fix that ?
Thanks in advance..!

**Comment by slackersoft** [comment]
Your tests should still run fine. These messages are probably coming because the version of Protractor that you're using isn't using the new `configure` function to set options, but the older individual functions. I'm re-opening jasmine/jasmine#1628 to fix the actual messages to make it more clear that tests will still run as before.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
Closing since we haven't heard anything new about this in quite some time, and it doesn't appear to be an issue with Jasmine.
