### ISSUE TITLE
NullInjectorError: No provider for StateFactory!

### ISSUE THREAD

**Issue by RoanKathrina** [jasmine/jasmine.github.io#122]
## Are you creating an issue in the correct repository?

- This repository is for the Jasmine docs. If you aren't reporting a documentation problem, you're probabl in the wrong place.
- When in doubt, create an issue in the [core Jasmine repo](https://github.com/jasmine/jasmine/issues).
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

**Comment by sgravrock** [comment]
Based on the title of this issue it looks like you're having trouble with some other library, not Jasmine. Since you're not reporting a problem with the Jasmine documentation, I'm going to go ahead and close this.

It looks like this is your first time logging an issue on Github. Here are a couple of tips that will help you get more helpful responses in the future:

* Try to track down which tool or library you're having trouble with. That can sometimes be difficult, but errors like the one mentioned in your title often come with a stack trace that can point you in the right direction.
* Read and follow the instructions that appear in the main text box when you create the issue. (In this case, everything after "Are you creating an issue in the correct repository?")
* Explain how to reproduce the problem. You can do this by writing a list of exact steps for others to follow or by creating a complete, minimal, running code sample that demonstrates the problem. Tools like https://codepen.io/ are good for this.
* Many projects prefer to use Github issues for bugs and new features only, and handle support requests elsewhere. You'll often get a better response if you ask for help on Stack Overflow or the project's mailing list.

I hope this helps.
