### ISSUE TITLE
missing documentation on how to use console reporter

### ISSUE THREAD

**Issue by Valve** [jasmine/jasmine.github.io#38]
I really cannot find this info, please fix it.

**Comment by slackersoft** [comment]
The `ConsoleReporter` in core has been deprecated as the only place that used it was jasmine-npm, which has now pulled it into its own repo. It is primarily an internal implementation detail and not really considered for external consumption.

That said, what exactly are you trying to do with it? This will help us figure out what kind of docs would be useful.

**Comment by Valve** [comment]
I've ended up using jasmine reporters project (https://github.com/larrymyers/jasmine-reporters).
But initially I just wanted to have jasmine specs to print results to Google Chrome console or to PhantomJS console, but couldn't find the docs about it.

**Comment by slackersoft** [comment]
The `ConsoleReporter` is not really designed for printing to a browser console. It colors its output for better display in a terminal.

It sounds like you've found a solution in jasmine-reporters, and since jasmine's `ConsoleReporter` isn't designed for your use case, I'm going to close this.

Thanks for using jasmine!
